# Generated by Django 3.1.12 on 2025-01-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supplier',
            table='inventory_supplier',
        ),
    ]
