# Generated by Django 3.1.12 on 2025-01-15 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20250115_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
